name: example
description: Demonstrates how to use the flutter_carousel_widget package.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_carousel_widget:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
