name: flutter_carousel_widget
description: A customizable Flutter carousel slider with infinite scroll, auto-scroll, custom widgets, animations, pre-built indicators, expandable widgets, and auto-sized child support.

version: 3.0.0

homepage: https://pub.dev/packages/flutter_carousel_widget
repository: https://github.com/nixrajput/flutter_carousel_widget
issue_tracker: https://github.com/nixrajput/flutter_carousel_widget/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^4.0.0
