name: Run Test Cases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.x

      - name: Run Flutter doctor
        run: flutter doctor -v

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup-flutter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Flutter Analyzer (Lint)
        run: flutter analyze

  test:
    name: Test Code
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Flutter Tests
        run: flutter test